export const ADD_FAVORITE_USERS = 'ADD_FAVORITE_USERS';
export const REMOVE_FAVORITE_USERS = 'REMOVE_FAVORITE_USERS';
export const GET_USERS = 'GET_USERS'
export const REMOVE_USER = 'REMOVE_USER'
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'
export const TOGGLE_IS_FAVORING_PROGRESS = 'TOGGLE_IS_FAVORING_PROGRESS'

export const SET_USER_DATA = 'ADD-SET_USER_DATA';


