export const ADD_FAVORITE_USERS = 'ADD_FAVORITE_USERS';
export const REMOVE_FAVORITE_USERS = 'REMOVE_FAVORITE_USERS';
export const SET_USERS = 'SET_USERS'
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'
