export const ADD_FAVORITE_USERS = 'USERS/ADD_FAVORITE_USERS';
export const REMOVE_FAVORITE_USERS = 'USERS/REMOVE_FAVORITE_USERS';
export const GET_USERS = 'USERS/GET_USERS'
export const REMOVE_USER = 'USERS/REMOVE_USER'
export const TOGGLE_IS_FETCHING = 'USERS/TOGGLE_IS_FETCHING'
export const TOGGLE_IS_FAVORING_PROGRESS = 'USERS/TOGGLE_IS_FAVORING_PROGRESS'
export const SET_USER_DATA = 'AUTH/ADD-SET_USER_DATA';


